### ISSUE TITLE
Algorithm going 0-999

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/app-ac-islandtracker#23]
Buy price: 103
Monday: 94/90
Goes weird immediatelly here... but here are the rest
Tuesday: 86/82
Wednesday 78/73

**Comment by jamesmontemagno** [comment]
@sparkie108 can you take a look at this. Maybe they have updated the algorithm a bit

**Comment by jamesmontemagno** [comment]
I think maybe the changed a lot of code recently.

**Comment by sparkie108** [comment]
This issue is that the predicted prices for Monday pm are in two ranges:
62-83
93-145
and 90 falls between them.
If you enter 90 into https://turnipprophet.io/ it shows 990,0 for Monday pm as well.

I'll review their changes at the weekend to see what needs to be updated, there's at least one issue to do with rounding that I need to copy.

**Comment by jamesmontemagno** [comment]
oh, this if fascinating. I see that TP shows patterns, but they are all at ---% which means they have no idea.... how do they still get possible odds back?

![image](https://user-images.githubusercontent.com/1676321/79389377-410a5300-7f23-11ea-8a1b-06e0b2107844.png)

**Comment by sparkie108** [comment]
It only shows odds if you enter last week’s pattern

**Comment by jamesmontemagno** [comment]
hmmmmmmm
i see.. interesting
I would say that in our app i see valid ranges: 
![image](https://user-images.githubusercontent.com/1676321/79390920-6dbf6a00-7f25-11ea-8284-2face459d05a.png)

**Comment by jamesmontemagno** [comment]
I think we should allow the previous weeks to be entered in and we should display the current trend as well.

I do find it odd though that here we see it is valid 61-145... so something is off there.

**Comment by sparkie108** [comment]
It’s a predicted range, only testers will enter random prices, actual prices will work fine.

I think we should keep it simple 99% of players won’t understand the four patterns.

I’ve based my sell timing on this for two weeks and the simple range is all I’ve needed so far.

**Comment by jamesmontemagno** [comment]
Oh, i should have mentioned that these were actual numbers from my friend using the app :)

**Comment by jamesmontemagno** [comment]
I think the best thing to do here is to basically say prediction unavaialble if we get 0-999

**Comment by sparkie108** [comment]
Then TP is wrong. I’m only trying to match TP. 

Prediction unavailable makes sense.

**Comment by jamesmontemagno** [comment]
I think that TP actually is showing that there are no predictable pattern, but they still show stuff in there... weird. I looked at their code and looks like they changed a bunch of stuff.

I will say locally here we have had good success :)

**Comment by sparkie108** [comment]
Most of their changes are to do with the % chance which I’m not convinced is appropriate for your app or even useful (based on two weeks usage).  But there are some bug fixes to the core predictions which I will incorporate.

**Comment by sparkie108** [comment]
But if we wan’t to keep things simple 0-999 is really the same as prediction unavailable with less to explain, like why is the prediction unavailable?

**Comment by sparkie108** [comment]
The latest version of TP now gives a result with these inputs:
https://turnipprophet.io?prices=103.94.90.86.82.78.73......
and I've just got my console app test version to work as well. 😸 
PR coming tomorrow.

**Comment by jamesmontemagno** [comment]
We could also break out some of the prediction stuff into a separate library and add some unit tests if you desire.

**Comment by sparkie108** [comment]
I think a separate library would be an overkill.  I have tested the latest PR against millions of patterns generated by the reverse engineered code and all is well, the code feels stable at this point.  If I'm proved wrong I will review.

**Comment by jamesmontemagno** [comment]
Closing this out! WHOOP WHOOP <3
