### ISSUE TITLE
Missing attribution and license

### ISSUE THREAD

**Issue by mikebryant** [jamesmontemagno/app-ac-islandtracker#29]
Hi, according to #9 the code in this project is derived from the code of my project here: https://github.com/mikebryant/ac-nh-turnip-prices/blob/master/js/predictions.js

However, this project doesn't include the required attribution from https://github.com/mikebryant/ac-nh-turnip-prices/blob/master/NOTICE, which should be both in this repository and visible in the application itself.

Also, this project doesn't include a copy of the required license text from https://github.com/mikebryant/ac-nh-turnip-prices/blob/master/LICENSE

Could you fix this please? :)

**Comment by jamesmontemagno** [comment]
Yes absolutely!

**Comment by jamesmontemagno** [comment]
Need to also add:
* [ ] Resizetizer.NT
* [ ] Xamarin.Essentials
* [ ] Xamarin.Forms
* [ ] Mvvmhelpers
* [ ] PancakeView
* [ ] Sharpnado
* [ ] MonkeyCache
* [ ] Custom Fonts

**Comment by jamesmontemagno** [comment]
Now on about page
![image](https://user-images.githubusercontent.com/1676321/80674904-f67eef80-8a67-11ea-9da7-5eceaf874c28.png)

**Comment by jamesmontemagno** [comment]
Added, uploaded, and merged in!

Also sponsored :)
