### ISSUE TITLE
App linking on Android seems not working

### ISSUE THREAD

**Issue by vittoso** [jamesmontemagno/app-ac-islandtracker#78]
Hi, I've just installed the Island Tracker in Android from google store, but looks like the app linking for Friend links is not working.

**Repro Steps:**
1 - have a friend code sent via IM (i.e. Telegram or WhatsApp)
2 - acislandtracker:// appears not to be recognized as link
3-  if I copy&paste link in chrome, it opens a google search instead of Island Traker app.

Maybe I am doing something wrong?

Island Tracker version 1.2
Android 10 (patches 10 march 2020)
Phone One Plus 7T (Oxygen OS 10.0.9.HD65BA)

**Comment by nicolapcweek94** [comment]
Additional data: in my case on iOS the link is not recognized as a link by Telegram but it is recognized as a link in Whatsapp. Clicking it (in Whatsapp) or copypasting it in Safari (from Telegram) correctly launches the app to send the friend request

Island Tracker v1.2 (116)
iOS 13.5
iPhone X

**Comment by jamesmontemagno** [comment]
Yeah, it is pretty tricky as each app and each OS handles it different. iMessage & Email seem to work great on iOS. On Android I haven't seen anything work yet :(. 

There are a few ways to open up the link;
1.) If it is a link, click it and the app will launch
2.) Android: Highlight the link and click the "share" icon to launch the app in the share sheet
3.) You can copy it to clipboard. Then open app and navigate to the "Friends" tab. This will launch the request.

I am open to how to improve this flow as well.

**Comment by jamesmontemagno** [comment]
In the next version I think I will kind of stream line this to make it easier to copy/paste into the app:
![addfriend](https://user-images.githubusercontent.com/1676321/82842759-95dcaa00-9e8f-11ea-9eed-fa41848d9c5e.gif)

**Comment by jamesmontemagno** [comment]
1.3 has shipped and adds in this button to help streamline the copy/paste scenario.
